use strict;
use warnings;

use File::Spec;
use File::Temp qw(tempdir);
use FindBin qw($Bin);
use Test::More;

# Gene-catalogue clustering must keep fragments with the gene they came from,
# but must not merge genes that only share a short local block. The mmseqs2
# commands are generated by geneCat.pl::clusterFNA; the second half of this test
# runs them on a synthetic fixture when mmseqs2 is installed.

my $root = File::Spec->rel2abs(File::Spec->catdir($Bin, '..'));
my $script = File::Spec->catfile($root, 'secScripts', 'geneCat.pl');
open my $fh, '<', $script or die "Cannot read $script: $!";
my $source = do { local $/; <$fh> };
close $fh;
my ($clusterFNA) = $source =~ /^(sub clusterFNA\s*\([^)]*\)\s*\{.*?^\})/ms;
BAIL_OUT('Cannot isolate clusterFNA from geneCat.pl') unless defined $clusterFNA;

my $mmseqs = '';
for my $dir (split /:/, $ENV{PATH} // '') {
	my $candidate = File::Spec->catfile($dir, 'mmseqs');
	if (-x $candidate) { $mmseqs = $candidate; last; }
}
{
	package GeneCatClusterTest;
	our ($mmseqs2Bin, $rmBin, $mkdirBin, $mvBin, $cdhitBin) = ($mmseqs || 'mmseqs', 'rm', 'mkdir', 'mv', 'cd-hit-est');
	our $mmS2clstr = "$^X " . File::Spec->catfile($root, 'secScripts', 'GC', 'mmS2clstr.pl');
	sub getProgPaths { return $mmS2clstr if $_[0] eq 'mmS2clstr'; die "unexpected program $_[0]\n"; }
	eval "no warnings 'prototype'; $clusterFNA; 1" or die $@;
}

sub command {
	my ($aS, $aL, $greedy, $mm) = @_;
	return GeneCatClusterTest::clusterFNA('in.fna', 'out.fna', $aS, $aL, 95, 2, $greedy, 'tmp', $mm // 1, 10);
}

like(command(0.9, 0, 0), qr/easy-linclust .* -c 0\.9 --cov-mode 1 /,
	'catalogue clustering requires coverage of the shorter (member) gene');
like(command(0.9, 0, 1), qr/easy-cluster .* -c 0\.9 --cov-mode 1 /,
	'marker-gene clustering keeps its intended 90% shorter-gene coverage');
like(command(0, 0, 0), qr/ -c 0 --cov-mode 0 /,
	'a coverage of 0 disables the coverage filter');
like(command(0.8, 0.8, 0), qr/ -c 0\.8 --cov-mode 0 /,
	'coverage of the longer sequence maps to bidirectional coverage mode');
like(command(0.9, 0, 0), qr/--min-seq-id 0\.95 /, 'percent identity is converted to a fraction');
like(command(0.9, 0, 0, 0), qr/cd-hit-est .* -G 1 .* -aS 0\.9 -aL 0 /,
	'the CD-HIT back-end receives the same coverage request');

SKIP: {
	skip 'mmseqs2 is not installed', 4 unless $mmseqs;
	my $tmp = tempdir(CLEANUP => 1);
	srand(7);
	my @bases = qw(A C G T);
	my $random = sub { join '', map { $bases[int rand 4] } 1 .. $_[0] };
	my $mutate = sub {
		my ($sequence, $rate) = @_;
		my @s = split //, $sequence;
		for (@s) {
			next unless rand() < $rate;
			my $new; do { $new = $bases[int rand 4] } while $new eq $_; $_ = $new;
		}
		return join '', @s;
	};
	my $geneA = $random->(1500);
	my $geneB = $random->(1200);
	substr($geneB, 500, 150) = substr($geneA, 700, 150);   # shared local block only
	my %genes = (
		geneA       => $geneA,
		geneA_var97 => $mutate->($geneA, 0.03),              # same gene, 97% identity
		fragA       => $mutate->(substr($geneA, 200, 600), 0.01), # assembly fragment of geneA
		geneB       => $geneB,
		geneD       => $random->(900),
	);
	my $input = File::Spec->catfile($tmp, 'genes.fna');
	open my $out, '>', $input or die $!;
	print {$out} ">$_\n$genes{$_}\n" for sort { length($genes{$b}) <=> length($genes{$a}) || $a cmp $b } keys %genes;
	close $out;

	my $output = File::Spec->catfile($tmp, 'catalogue.fna');
	my $cmd = GeneCatClusterTest::clusterFNA($input, $output, 0.9, 0, 95, 1, 0,
		File::Spec->catdir($tmp, 'work'), 1, 1);
	my $log = File::Spec->catfile($tmp, 'mmseqs.log');
	is(system('bash', '-eo', 'pipefail', '-c', "($cmd) > '$log' 2>&1"), 0, 'generated mmseqs2 clustering runs')
		or diag(do { local (@ARGV, $/) = ($log); <> });

	my (%cluster_of, $current);
	open my $clstr, '<', "$output.clstr" or die "Cannot read $output.clstr: $!";
	while (my $line = <$clstr>) {
		if ($line =~ /^>Cluster (\d+)/) { $current = $1; next; }
		$cluster_of{$1} = $current if $line =~ />(\S+?)\.\.\./;
	}
	close $clstr;
	is($cluster_of{fragA}, $cluster_of{geneA}, 'a fragment contained in a gene joins that gene');
	is($cluster_of{geneA_var97}, $cluster_of{geneA}, 'a 97%-identical full-length copy joins the gene');
	isnt($cluster_of{geneB}, $cluster_of{geneA},
		'a gene sharing only a 150 nt block is not merged into another gene');
}

done_testing();
